# Gathering Data

In [2]:
import pandas as pd
import requests
import os
import numpy as np

### 1. Read data from local csv file

In [3]:
twitter_archive = pd.read_csv('twitter-archive-enhanced .csv')
twitter_archive.head()

FileNotFoundError: [Errno 2] File b'twitter-archive-enhanced.csv' does not exist: b'twitter-archive-enhanced.csv'

In [3]:
twitter_archive.expanded_urls[1]

'https://twitter.com/dog_rates/status/892177421306343426/photo/1'

In [4]:
twitter_archive.shape

(2356, 17)

In [5]:
twitter_archive.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2356 entries, 0 to 2355
Data columns (total 17 columns):
tweet_id                      2356 non-null int64
in_reply_to_status_id         78 non-null float64
in_reply_to_user_id           78 non-null float64
timestamp                     2356 non-null object
source                        2356 non-null object
text                          2356 non-null object
retweeted_status_id           181 non-null float64
retweeted_status_user_id      181 non-null float64
retweeted_status_timestamp    181 non-null object
expanded_urls                 2297 non-null object
rating_numerator              2356 non-null int64
rating_denominator            2356 non-null int64
name                          2356 non-null object
doggo                         2356 non-null object
floofer                       2356 non-null object
pupper                        2356 non-null object
puppo                         2356 non-null object
dtypes: float64(4), int64(3), object(10)
memory usage: 313.0+ KB

### 3. Download data from url

In [6]:
folder_name = 'twitter_image_prediction'
if not os.path.exists(folder_name):
    os.makedirs(folder_name)

In [7]:
url = ' https://d17h27t6h515a5.cloudfront.net/topher/2017/August/599fd2ad_image-predictions/image-predictions.tsv'
response = requests.get(url)
with open(os.path.join(folder_name, url.split('/')[-1]), mode = 'wb') as file:
    file.write(response.content)

In [8]:
image_predictions = pd.read_csv('twitter_image_prediction/image-predictions.tsv', sep = '\t')

In [9]:
image_predictions.head()

,tweet_id,jpg_url,img_num,p1,p1_conf,p1_dog,p2,p2_conf,p2_dog,p3,p3_conf,p3_dog
0,666020888022790149,https://pbs.twimg.com/media/CT4udn0WwAA0aMy.jpg,1,Welsh_springer_spaniel,0.465074,True,collie,0.156665,True,Shetland_sheepdog,0.061428,True
1,666029285002620928,https://pbs.twimg.com/media/CT42GRgUYAA5iDo.jpg,1,redbone,0.506826,True,miniature_pinscher,0.074192,True,Rhodesian_ridgeback,0.072010,True
2,666033412701032449,https://pbs.twimg.com/media/CT4521TWwAEvMyu.jpg,1,German_shepherd,0.596461,True,malinois,0.138584,True,bloodhound,0.116197,True
3,666044226329800704,https://pbs.twimg.com/media/CT5Dr8HUEAA-lEu.jpg,1,Rhodesian_ridgeback,0.408143,True,redbone,0.360687,True,miniature_pinscher,0.222752,True
4,666049248165822465,https://pbs.twimg.com/media/CT5IQmsXIAAKY4A.jpg,1,miniature_pinscher,0.560311,True,Rottweiler,0.243682,True,Doberman,0.154629,True

### 3. Query information such as reweets times, likes via tweepy API.

In [10]:
import tweepy
import json
import time

consumer_key = 'clmtJyZiMTEH0ZebVmL7HHXbY'
consumer_secret = 'l5gMKRHsglLlDMJ9kKYzz1aTzoVTwC89sQJ6fs3lZCbkoRfSgT'
access_token = '1177482851337396225-GcMcgClLxMia7M7WCARLNeuqTVrbTZ'
access_secret = 'B8fuuiApifsVw6MO1r4jpxoxpPimEEoOxT9ovuAYgQCr1'

auth = tweepy.OAuthHandler(consumer_key, consumer_secret)
auth.set_access_token(access_token, access_secret)

api = tweepy.API(auth,parser=tweepy.parsers.JSONParser())

In [11]:
tweet_data1 = api.get_status(666020888022790149, tweet_mode='extended', wait_on_rate_limit = True, wait_on_rate_limit_notify = True)

In [12]:
tweet_data1

{'created_at': 'Sun Nov 15 22:32:08 +0000 2015',
 'id': 666020888022790149,
 'id_str': '666020888022790149',
 'full_text': 'Here we have a Japanese Irish Setter. Lost eye in Vietnam (?). Big fan of relaxing on stair. 8/10 would pet https://t.co/BLDqew2Ijj',
 'truncated': False,
 'display_text_range': [0, 131],
 'entities': {'hashtags': [],
  'symbols': [],
  'user_mentions': [],
  'urls': [],
  'media': [{'id': 666020881337073664,
    'id_str': '666020881337073664',
    'indices': [108, 131],
    'media_url': 'http://pbs.twimg.com/media/CT4udn0WwAA0aMy.jpg',
    'media_url_https': 'https://pbs.twimg.com/media/CT4udn0WwAA0aMy.jpg',
    'url': 'https://t.co/BLDqew2Ijj',
    'display_url': 'pic.twitter.com/BLDqew2Ijj',
    'expanded_url': 'https://twitter.com/dog_rates/status/666020888022790149/photo/1',
    'type': 'photo',
    'sizes': {'medium': {'w': 960, 'h': 720, 'resize': 'fit'},
     'thumb': {'w': 150, 'h': 150, 'resize': 'crop'},
     'large': {'w': 960, 'h': 720, 'resize': 'fit'},
     'small': {'w': 680, 'h': 510, 'resize': 'fit'}}}]},
 'extended_entities': {'media': [{'id': 666020881337073664,
    'id_str': '666020881337073664',
    'indices': [108, 131],
    'media_url': 'http://pbs.twimg.com/media/CT4udn0WwAA0aMy.jpg',
    'media_url_https': 'https://pbs.twimg.com/media/CT4udn0WwAA0aMy.jpg',
    'url': 'https://t.co/BLDqew2Ijj',
    'display_url': 'pic.twitter.com/BLDqew2Ijj',
    'expanded_url': 'https://twitter.com/dog_rates/status/666020888022790149/photo/1',
    'type': 'photo',
    'sizes': {'medium': {'w': 960, 'h': 720, 'resize': 'fit'},
     'thumb': {'w': 150, 'h': 150, 'resize': 'crop'},
     'large': {'w': 960, 'h': 720, 'resize': 'fit'},
     'small': {'w': 680, 'h': 510, 'resize': 'fit'}}}]},
 'source': '<a href="http://twitter.com/download/iphone" rel="nofollow">Twitter for iPhone</a>',
 'in_reply_to_status_id': None,
 'in_reply_to_status_id_str': None,
 'in_reply_to_user_id': None,
 'in_reply_to_user_id_str': None,
 'in_reply_to_screen_name': None,
 'user': {'id': 4196983835,
  'id_str': '4196983835',
  'name': 'WeRateDogs®',
  'screen_name': 'dog_rates',
  'location': '「 DM YOUR DOGS 」',
  'description': 'Your Only Source For Professional Dog Ratings Instagram and Facebook ➪ WeRateDogs partnerships@weratedogs.com ⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀',
  'url': 'https://t.co/N7sNNHAEXS',
  'entities': {'url': {'urls': [{'url': 'https://t.co/N7sNNHAEXS',
      'expanded_url': 'http://weratedogs.com',
      'display_url': 'weratedogs.com',
      'indices': [0, 23]}]},
   'description': {'urls': []}},
  'protected': False,
  'followers_count': 8769736,
  'friends_count': 15,
  'listed_count': 7267,
  'created_at': 'Sun Nov 15 21:41:29 +0000 2015',
  'favourites_count': 145944,
  'utc_offset': None,
  'time_zone': None,
  'geo_enabled': True,
  'verified': True,
  'statuses_count': 12090,
  'lang': None,
  'contributors_enabled': False,
  'is_translator': False,
  'is_translation_enabled': False,
  'profile_background_color': '000000',
  'profile_background_image_url': 'http://abs.twimg.com/images/themes/theme1/bg.png',
  'profile_background_image_url_https': 'https://abs.twimg.com/images/themes/theme1/bg.png',
  'profile_background_tile': False,
  'profile_image_url': 'http://pbs.twimg.com/profile_images/1218319284557905920/ntuD-LOA_normal.jpg',
  'profile_image_url_https': 'https://pbs.twimg.com/profile_images/1218319284557905920/ntuD-LOA_normal.jpg',
  'profile_banner_url': 'https://pbs.twimg.com/profile_banners/4196983835/1586206146',
  'profile_link_color': 'F5ABB5',
  'profile_sidebar_border_color': '000000',
  'profile_sidebar_fill_color': '000000',
  'profile_text_color': '000000',
  'profile_use_background_image': False,
  'has_extended_profile': False,
  'default_profile': False,
  'default_profile_image': False,
  'following': False,
  'follow_request_sent': False,
  'notifications': False,
  'translator_type': 'none'},
 'geo': None,
 'coordinates': None,
 'place': None,
 'contributors': None,
 'is_quote_status': False,
 'retweet_count': 463,
 'favorite_count': 2422,
 'favorited': False,
 'retweeted': False,
 'possibly_sensitive': False,
 'possibly_sensitive_appealable': False,
 'lang': 'en'}

In [ ]:
start = time.time()
tweet_ids = twitter_archive.tweet_id
tweet_data = []
tweet_success = []
tweet_failure = []

for tweet_id in tweet_ids:
    try: 
        tweet_data.append(api.get_status(tweet_id, tweet_mode='extended', 
                                  wait_on_rate_limit = True, 
                                  wait_on_rate_limit_notify = True))
        tweet_success.append(tweet_id)
    except:
        tweet_failure.append(tweet_id)
        print(tweet_id)
        
end = time.time()
print(end - start)

888202515573088257

In [ ]:
len(tweet_failure)

In [ ]:
len(tweet_success)

In [ ]:
with open('tweet_json.txt', mode = 'w') as file:
    json.dump(tweet_data, file)

In [ ]:
tweet_df = pd.read_json('tweet_json.txt')

In [ ]:
tweet_df['tweet_id']= tweet_success

In [ ]:
tweet_df= tweet_df[['tweet_id','favorite_count','retweet_count']]

In [ ]:
tweet_df.head()

In [ ]:
tweet_df.to_pickle('tweet_df.pkl')

In [10]:
tweet_df = pd.read_pickle('tweet_df.pkl')

# Assessing Data

In [11]:
# Display twitter_archive
twitter_archive

,tweet_id,in_reply_to_status_id,in_reply_to_user_id,timestamp,source,text,retweeted_status_id,retweeted_status_user_id,retweeted_status_timestamp,expanded_urls,rating_numerator,rating_denominator,name,doggo,floofer,pupper,puppo
0,892420643555336193,NaN,NaN,2017-08-01 16:23:56 +0000,"<a href=""http://twitter.com/download/iphone"" r...",This is Phineas. He's a mystical boy. Only eve...,NaN,NaN,NaN,https://twitter.com/dog_rates/status/892420643...,13,10,Phineas,None,None,None,None
1,892177421306343426,NaN,NaN,2017-08-01 00:17:27 +0000,"<a href=""http://twitter.com/download/iphone"" r...",This is Tilly. She's just checking pup on you....,NaN,NaN,NaN,https://twitter.com/dog_rates/status/892177421...,13,10,Tilly,None,None,None,None
2,891815181378084864,NaN,NaN,2017-07-31 00:18:03 +0000,"<a href=""http://twitter.com/download/iphone"" r...",This is Archie. He is a rare Norwegian Pouncin...,NaN,NaN,NaN,https://twitter.com/dog_rates/status/891815181...,12,10,Archie,None,None,None,None
3,891689557279858688,NaN,NaN,2017-07-30 15:58:51 +0000,"<a href=""http://twitter.com/download/iphone"" r...",This is Darla. She commenced a snooze mid meal...,NaN,NaN,NaN,https://twitter.com/dog_rates/status/891689557...,13,10,Darla,None,None,None,None
4,891327558926688256,NaN,NaN,2017-07-29 16:00:24 +0000,"<a href=""http://twitter.com/download/iphone"" r...",This is Franklin. He would like you to stop ca...,NaN,NaN,NaN,https://twitter.com/dog_rates/status/891327558...,12,10,Franklin,None,None,None,None
5,891087950875897856,NaN,NaN,2017-07-29 00:08:17 +0000,"<a href=""http://twitter.com/download/iphone"" r...",Here we have a majestic great white breaching ...,NaN,NaN,NaN,https://twitter.com/dog_rates/status/891087950...,13,10,None,None,None,None,None
6,890971913173991426,NaN,NaN,2017-07-28 16:27:12 +0000,"<a href=""http://twitter.com/download/iphone"" r...",Meet Jax. He enjoys ice cream so much he gets ...,NaN,NaN,NaN,"https://gofundme.com/ydvmve-surgery-for-jax,ht...",13,10,Jax,None,None,None,None
7,890729181411237888,NaN,NaN,2017-07-28 00:22:40 +0000,"<a href=""http://twitter.com/download/iphone"" r...",When you watch your owner call another dog a g...,NaN,NaN,NaN,https://twitter.com/dog_rates/status/890729181...,13,10,None,None,None,None,None
8,890609185150312448,NaN,NaN,2017-07-27 16:25:51 +0000,"<a href=""http://twitter.com/download/iphone"" r...",This is Zoey. She doesn't want to be one of th...,NaN,NaN,NaN,https://twitter.com/dog_rates/status/890609185...,13,10,Zoey,None,None,None,None
9,890240255349198849,NaN,NaN,2017-07-26 15:59:51 +0000,"<a href=""http://twitter.com/download/iphone"" r...",This is Cassie. She is a college pup. Studying...,NaN,NaN,NaN,https://twitter.com/dog_rates/status/890240255...,14,10,Cassie,doggo,None,None,None
10,890006608113172480,NaN,NaN,2017-07-26 00:31:25 +0000,"<a href=""http://twitter.com/download/iphone"" r...",This is Koda. He is a South Australian decksha...,NaN,NaN,NaN,https://twitter.com/dog_rates/status/890006608...,13,10,Koda,None,None,None,None
11,889880896479866881,NaN,NaN,2017-07-25 16:11:53 +0000,"<a href=""http://twitter.com/download/iphone"" r...",This is Bruno. He is a service shark. Only get...,NaN,NaN,NaN,https://twitter.com/dog_rates/status/889880896...,13,10,Bruno,None,None,None,None
12,889665388333682689,NaN,NaN,2017-07-25 01:55:32 +0000,"<a href=""http://twitter.com/download/iphone"" r...",Here's a puppo that seems to be on the fence a...,NaN,NaN,NaN,https://twitter.com/dog_rates/status/889665388...,13,10,None,None,None,None,puppo
13,889638837579907072,NaN,NaN,2017-07-25 00:10:02 +0000,"<a href=""http://twitter.com/download/iphone"" r...",This is Ted. He does his best. Sometimes that'...,NaN,NaN,NaN,https://twitter.com/dog_rates/status/889638837...,12,10,Ted,None,None,None,None
14,889531135344209921,NaN,NaN,2017-07-24 17:02:04 +0000,"<a href=""http://twitter.com/download/iphone"" r...",This is Stuart. He's sporting his favorite fan...,NaN,NaN,NaN,https://twitter.com/dog_rates/status/889531135...,13,10,Stuart,None,None,None,puppo
15,889278841981685760,NaN,NaN,2017-07-24 00:19:32 +0000,"<a href=""http://twitter.com/download/iphone"" r...",This is Oliver. You're witnessing one of his m...,NaN,NaN,NaN,https://twitter.com/dog_rates/status/889278841...,13,10,Oliver,None,None,None,None
16,888917238123831296,NaN,NaN,2017-07-23 00:22:39 +0000,"<a href=""http://twitter.com/download/iphone"" r...",This is Jim. He found a fren. Taught him how t...,NaN,NaN,NaN,https://twitter.com/dog_rates/status/888917238...,12,10,Jim,None,None,None,None
17,888804989199671297,NaN,NaN,2017-07-22 16:56:37 +0000,"<a href=""http://twitter.com/download/iphone"" r...",This is Zeke. He has a new stick. Very proud o...,NaN,NaN,NaN,https://twitter.com/dog_rates/status/888804989...,13,10,Zeke,None,None,None,None
18,888554962724278272,NaN,NaN,2017-07-22 00:23:06 +0000,"<a href=""http://twitter.com/download/iphone"" r...",This is Ralphus. He's powering up. Attempting ...,NaN,NaN,NaN,https://twitter.com/dog_rates/status/888554962...,13,10,Ralphus,None,None,None,None
19,888202515573088257,NaN,NaN,2017-07-21 01:02:36 +0000,"<a href=""http://twitter.com/download/iphone"" r...",RT @dog_rates: This is Canela. She attempted s...,8.874740e+17,4.196984e+09,2017-07-19 00:47:34 +0000,https://twitter.com/dog_rates/status/887473957...,13,10,Canela,None,None,None,None
20,888078434458587136,NaN,NaN,2017-07-20 16:49:33 +0000,"<a href=""http://twitter.com/download/iphone"" r...",This is Gerald. He was just told he didn't get...,NaN,NaN,NaN,https://twitter.com/dog_rates/status/888078434...,12,10,Gerald,None,None,None,None
21,887705289381826560,NaN,NaN,2017-07-19 16:06:48 +0000,"<a href=""http://twitter.com/download/iphone"" r...",This is Jeffrey. He has a monopoly on the pool...,NaN,NaN,NaN,https://twitter.com/dog_rates/status/887705289...,13,10,Jeffrey,None,None,None,None
22,887517139158093824,NaN,NaN,2017-07-19 03:39:09 +0000,"<a href=""http://twitter.com/download/iphone"" r...",I've yet to rate a Venezuelan Hover Wiener. Th...,NaN,NaN,NaN,https://twitter.com/dog_rates/status/887517139...,14,10,such,None,None,None,None
23,887473957103951883,NaN,NaN,2017-07-19 00:47:34 +0000,"<a href=""http://twitter.com/download/iphone"" r...",This is Canela. She attempted some fancy porch...,NaN,NaN,NaN,https://twitter.com/dog_rates/status/887473957...,13,10,Canela,None,None,None,None
24,887343217045368832,NaN,NaN,2017-07-18 16:08:03 +0000,"<a href=""http://twitter.com/download/iphone"" r...",You may not have known you needed to see this ...,NaN,NaN,NaN,https://twitter.com/dog_rates/status/887343217...,13,10,None,None,None,None,None
25,887101392804085760,NaN,NaN,2017-07-18 00:07:08 +0000,"<a href=""http://twitter.com/download/iphone"" r...",This... is a Jubilant Antarctic House Bear. We...,NaN,NaN,NaN,https://twitter.com/dog_rates/status/887101392...,12,10,None,None,None,None,None
26,886983233522544640,NaN,NaN,2017-07-17 16:17:36 +0000,"<a href=""http://twitter.com/download/iphone"" r...",This is Maya. She's very shy. Rarely leaves he...,NaN,NaN,NaN,https://twitter.com/dog_rates/status/886983233...,13,10,Maya,None,None,None,None
27,886736880519319552,NaN,NaN,2017-07-16 23:58:41 +0000,"<a href=""http://twitter.com/download/iphone"" r...",This is Mingus. He's a wonderful father to his...,NaN,NaN,NaN,"https://www.gofundme.com/mingusneedsus,https:/...",13,10,Mingus,None,None,None,None
28,886680336477933568,NaN,NaN,2017-07-16 20:14:00 +0000,"<a href=""http://twitter.com/download/iphone"" r...",This is Derek. He's late for a dog meeting. 13...,NaN,NaN,NaN,https://twitter.com/dog_rates/status/886680336...,13,10,Derek,None,None,None,None
29,886366144734445568,NaN,NaN,2017-07-15 23:25:31 +0000,"<a href=""http://twitter.com/download/iphone"" r...",This is Roscoe. Another pupper fallen victim t...,NaN,NaN,NaN,https://twitter.com/dog_rates/status/886366144...,12,10,Roscoe,None,None,pupper,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2326,666411507551481857,NaN,NaN,2015-11-17 00:24:19 +0000,"<a href=""http://twitter.com/download/iphone"" r...",This is quite the dog. Gets really excited whe...,NaN,NaN,NaN,https://twitter.com/dog_rates/status/666411507...,2,10,quite,None,None,None,None
2327,666407126856765440,NaN,NaN,2015-11-17 00:06:54 +0000,"<a href=""http://twitter.com/download/iphone"" r...",This is a southern Vesuvius bumblegruff. Can d...,NaN,NaN,NaN,https://twitter.com/dog_rates/status/666407126...,7,10,a,None,None,None,None
2328,666396247373291520,NaN,NaN,2015-11-16 23:23:41 +0000,"<a href=""http://twitter.com/download/iphone"" r...",Oh goodness. A super rare northeast Qdoba kang...,NaN,NaN,NaN,https://twitter.com/dog_rates/status/666396247...,9,10,None,None,None,None,None
2329,666373753744588802,NaN,NaN,2015-11-16 21:54:18 +0000,"<a href=""http://twitter.com/download/iphone"" r...",Those are sunglasses and a jean jacket. 11/10 ...,NaN,NaN,NaN,https://twitter.com/dog_rates/status/666373753...,11,10,None,None,None,None,None
2330,666362758909284353,NaN,NaN,2015-11-16 21:10:36 +0000,"<a href=""http://twitter.com/download/iphone"" r...",Unique dog here. Very small. Lives in containe...,NaN,NaN,NaN,https://twitter.com/dog_rates/status/666362758...,6,10,None,None,None,None,None
2331,666353288456101888,NaN,NaN,2015-11-16 20:32:58 +0000,"<a href=""http://twitter.com/download/iphone"" r...",Here we have a mixed Asiago from the Galápagos...,NaN,NaN,NaN,https://twitter.com/dog_rates/status/666353288...,8,10,None,None,None,None,None
2332,666345417576210432,NaN,NaN,2015-11-16 20:01:42 +0000,"<a href=""http://twitter.com/download/iphone"" r...",Look at this jokester thinking seat belt laws ...,NaN,NaN,NaN,https://twitter.com/dog_rates/status/666345417...,10,10,None,None,None,None,None
2333,666337882303524864,NaN,NaN,2015-11-16 19:31:45 +0000,"<a href=""http://twitter.com/download/iphone"" r...",This is an extremely rare horned Parthenon. No...,NaN,NaN,NaN,https://twitter.com/dog_rates/status/666337882...,9,10,an,None,None,None,None
2334,666293911632134144,NaN,NaN,2015-11-16 16:37:02 +0000,"<a href=""http://twitter.com/download/iphone"" r...",This is a funny dog. Weird toes. Won't come do...,NaN,NaN,NaN,https://twitter.com/dog_rates/status/666293911...,3,10,a,None,None,None,None
2335,666287406224695296,NaN,NaN,2015-11-16 16:11:11 +0000,"<a href=""http://twitter.com/download/iphone"" r...",This is an Albanian 3 1/2 legged Episcopalian...,NaN,NaN,NaN,https://twitter.com/dog_rates/status/666287406...,1,2,an,None,None,None,None
2336,666273097616637952,NaN,NaN,2015-11-16 15:14:19 +0000,"<a href=""http://twitter.com/download/iphone"" r...",Can take selfies 11/10 https://t.co/ws2AMaNwPW,NaN,NaN,NaN,https://twitter.com/dog_rates/status/666273097...,11,10,None,None,None,None,None
2337,666268910803644416,NaN,NaN,2015-11-16 14:57:41 +0000,"<a href=""http://twitter.com/download/iphone"" r...",Very concerned about fellow dog trapped in com...,NaN,NaN,NaN,https://twitter.com/dog_rates/status/666268910...,10,10,None,None,None,None,None
2338,666104133288665088,NaN,NaN,2015-11-16 04:02:55 +0000,"<a href=""http://twitter.com/download/iphone"" r...",Not familiar with this breed. No tail (weird)....,NaN,NaN,NaN,https://twitter.com/dog_rates/status/666104133...,1,10,None,None,None,None,None
2339,666102155909144576,NaN,NaN,2015-11-16 03:55:04 +0000,"<a href=""http://twitter.com/download/iphone"" r...",Oh my. Here you are seeing an Adobe Setter giv...,NaN,NaN,NaN,https://twitter.com/dog_rates/status/666102155...,11,10,None,None,None,None,None
2340,666099513787052032,NaN,NaN,2015-11-16 03:44:34 +0000,"<a href=""http://twitter.com/download/iphone"" r...",Can stand on stump for what seems like a while...,NaN,NaN,NaN,https://twitter.com/dog_rates/status/666099513...,8,10,None,None,None,None,None
2341,666094000022159362,NaN,NaN,2015-11-16 03:22:39 +0000,"<a href=""http://twitter.com/download/iphone"" r...",This appears to be a Mongolian Presbyterian mi...,NaN,NaN,NaN,https://twitter.com/dog_rates/status/666094000...,9,10,None,None,None,None,None
2342,666082916733198337,NaN,NaN,2015-11-16 02:38:37 +0000,"<a href=""http://twitter.com/download/iphone"" r...",Here we have a well-established sunblockerspan...,NaN,NaN,NaN,https://twitter.com/dog_rates/status/666082916...,6,10,None,None,None,None,None
2343,666073100786774016,NaN,NaN,2015-11-16 01:59:36 +0000,"<a href=""http://twitter.com/download/iphone"" r...",Let's hope this flight isn't Malaysian (lol). ...,NaN,NaN,NaN,https://twitter.com/dog_rates/status/666073100...,10,10,None,None,None,None,None
2344,666071193221509120,NaN,NaN,2015-11-16 01:52:02 +0000,"<a href=""http://twitter.com/download/iphone"" r...",Here we have a northern speckled Rhododendron....,NaN,NaN,NaN,https://twitter.com/dog_rates/status/666071193...,9,10,None,None,None,None,None
2345,666063827256086533,NaN,NaN,2015-11-16 01:22:45 +0000,"<a href=""http://twitter.com/download/iphone"" r...",This is the happiest dog you will ever see. Ve...,NaN,NaN,NaN,https://twitter.com/dog_rates/status/666063827...,10,10,the,None,None,None,None
2346,666058600524156928,NaN,NaN,2015-11-16 01:01:59 +0000,"<a href=""http://twitter.com/download/iphone"" r...",Here is the Rand Paul of retrievers folks! He'...,NaN,NaN,NaN,https://twitter.com/dog_rates/status/666058600...,8,10,the,None,None,None,None
2347,666057090499244032,NaN,NaN,2015-11-16 00:55:59 +0000,"<a href=""http://twitter.com/download/iphone"" r...",My oh my. This is a rare blond Canadian terrie...,NaN,NaN,NaN,https://twitter.com/dog_rates/status/666057090...,9,10,a,None,None,None,None
2348,666055525042405380,NaN,NaN,2015-11-16 00:49:46 +0000,"<a href=""http://twitter.com/download/iphone"" r...",Here is a Siberian heavily armored polar bear ...,NaN,NaN,NaN,https://twitter.com/dog_rates/status/666055525...,10,10,a,None,None,None,None
2349,666051853826850816,NaN,NaN,2015-11-16 00:35:11 +0000,"<a href=""http://twitter.com/download/iphone"" r...",This is an odd dog. Hard on the outside but lo...,NaN,NaN,NaN,https://twitter.com/dog_rates/status/666051853...,2,10,an,None,None,None,None
2350,666050758794694657,NaN,NaN,2015-11-16 00:30:50 +0000,"<a href=""http://twitter.com/download/iphone"" r...",This is a truly beautiful English Wilson Staff...,NaN,NaN,NaN,https://twitter.com/dog_rates/status/666050758...,10,10,a,None,None,None,None
2351,666049248165822465,NaN,NaN,2015-11-16 00:24:50 +0000,"<a href=""http://twitter.com/download/iphone"" r...",Here we have a 1949 1st generation vulpix. Enj...,NaN,NaN,NaN,https://twitter.com/dog_rates/status/666049248...,5,10,None,None,None,None,None
2352,666044226329800704,NaN,NaN,2015-11-16 00:04:52 +0000,"<a href=""http://twitter.com/download/iphone"" r...",This is a purebred Piers Morgan. Loves to Netf...,NaN,NaN,NaN,https://twitter.com/dog_rates/status/666044226...,6,10,a,None,None,None,None
2353,666033412701032449,NaN,NaN,2015-11-15 23:21:54 +0000,"<a href=""http://twitter.com/download/iphone"" r...",Here is a very happy pup. Big fan of well-main...,NaN,NaN,NaN,https://twitter.com/dog_rates/status/666033412...,9,10,a,None,None,None,None
2354,666029285002620928,NaN,NaN,2015-11-15 23:05:30 +0000,"<a href=""http://twitter.com/download/iphone"" r...",This is a western brown Mitsubishi terrier. Up...,NaN,NaN,NaN,https://twitter.com/dog_rates/status/666029285...,7,10,a,None,None,None,None
2355,666020888022790149,NaN,NaN,2015-11-15 22:32:08 +0000,"<a href=""http://twitter.com/download/iphone"" r...",Here we have a Japanese Irish Setter. Lost eye...,NaN,NaN,NaN,https://twitter.com/dog_rates/status/666020888...,8,10,None,None,None,None,None

In [12]:
twitter_archive.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2356 entries, 0 to 2355
Data columns (total 17 columns):
tweet_id                      2356 non-null int64
in_reply_to_status_id         78 non-null float64
in_reply_to_user_id           78 non-null float64
timestamp                     2356 non-null object
source                        2356 non-null object
text                          2356 non-null object
retweeted_status_id           181 non-null float64
retweeted_status_user_id      181 non-null float64
retweeted_status_timestamp    181 non-null object
expanded_urls                 2297 non-null object
rating_numerator              2356 non-null int64
rating_denominator            2356 non-null int64
name                          2356 non-null object
doggo                         2356 non-null object
floofer                       2356 non-null object
pupper                        2356 non-null object
puppo                         2356 non-null object
dtypes: float64(4), int64(3), object(10)
memory usage: 313.0+ KB

In [13]:
sum(twitter_archive.duplicated())

0

In [16]:
twitter_archive.rating_numerator.value_counts()

12      558
11      464
10      461
13      351
9       158
8       102
7        55
14       54
5        37
6        32
3        19
4        17
1         9
2         9
420       2
0         2
15        2
75        2
80        1
20        1
24        1
26        1
44        1
50        1
60        1
165       1
84        1
88        1
144       1
182       1
143       1
666       1
960       1
1776      1
17        1
27        1
45        1
99        1
121       1
204       1
Name: rating_numerator, dtype: int64

In [17]:
twitter_archive.rating_denominator.value_counts()

10     2333
11        3
50        3
80        2
20        2
2         1
16        1
40        1
70        1
15        1
90        1
110       1
120       1
130       1
150       1
170       1
7         1
0         1
Name: rating_denominator, dtype: int64

`twitter_archive` columns:

- **Completeness:** 
    - in_reply_to_status_id, in_reply_to_user_id, retweeted_status_id, retweeted_status_user_id, retweeted_status_timestamp, expanded_urls have missing data on those columns.
- **Validity:** 
    - Some rating numbers in rating_number column are too large comparing to other rating number, such as 666; Some rating number is less than 10 which is not compliant to the rule.
    - Some denominator have invalid values.
- **Accuracy:**
    - retweeted_status_timestamp, timestamp should be datetime instead of object (string).
    - Name column have invalid names i.e 'None', 'a', 'an' and less than 3 characters.

In [14]:
image_predictions

,tweet_id,jpg_url,img_num,p1,p1_conf,p1_dog,p2,p2_conf,p2_dog,p3,p3_conf,p3_dog
0,666020888022790149,https://pbs.twimg.com/media/CT4udn0WwAA0aMy.jpg,1,Welsh_springer_spaniel,0.465074,True,collie,0.156665,True,Shetland_sheepdog,0.061428,True
1,666029285002620928,https://pbs.twimg.com/media/CT42GRgUYAA5iDo.jpg,1,redbone,0.506826,True,miniature_pinscher,0.074192,True,Rhodesian_ridgeback,0.072010,True
2,666033412701032449,https://pbs.twimg.com/media/CT4521TWwAEvMyu.jpg,1,German_shepherd,0.596461,True,malinois,0.138584,True,bloodhound,0.116197,True
3,666044226329800704,https://pbs.twimg.com/media/CT5Dr8HUEAA-lEu.jpg,1,Rhodesian_ridgeback,0.408143,True,redbone,0.360687,True,miniature_pinscher,0.222752,True
4,666049248165822465,https://pbs.twimg.com/media/CT5IQmsXIAAKY4A.jpg,1,miniature_pinscher,0.560311,True,Rottweiler,0.243682,True,Doberman,0.154629,True
5,666050758794694657,https://pbs.twimg.com/media/CT5Jof1WUAEuVxN.jpg,1,Bernese_mountain_dog,0.651137,True,English_springer,0.263788,True,Greater_Swiss_Mountain_dog,0.016199,True
6,666051853826850816,https://pbs.twimg.com/media/CT5KoJ1WoAAJash.jpg,1,box_turtle,0.933012,False,mud_turtle,0.045885,False,terrapin,0.017885,False
7,666055525042405380,https://pbs.twimg.com/media/CT5N9tpXIAAifs1.jpg,1,chow,0.692517,True,Tibetan_mastiff,0.058279,True,fur_coat,0.054449,False
8,666057090499244032,https://pbs.twimg.com/media/CT5PY90WoAAQGLo.jpg,1,shopping_cart,0.962465,False,shopping_basket,0.014594,False,golden_retriever,0.007959,True
9,666058600524156928,https://pbs.twimg.com/media/CT5Qw94XAAA_2dP.jpg,1,miniature_poodle,0.201493,True,komondor,0.192305,True,soft-coated_wheaten_terrier,0.082086,True
10,666063827256086533,https://pbs.twimg.com/media/CT5Vg_wXIAAXfnj.jpg,1,golden_retriever,0.775930,True,Tibetan_mastiff,0.093718,True,Labrador_retriever,0.072427,True
11,666071193221509120,https://pbs.twimg.com/media/CT5cN_3WEAAlOoZ.jpg,1,Gordon_setter,0.503672,True,Yorkshire_terrier,0.174201,True,Pekinese,0.109454,True
12,666073100786774016,https://pbs.twimg.com/media/CT5d9DZXAAALcwe.jpg,1,Walker_hound,0.260857,True,English_foxhound,0.175382,True,Ibizan_hound,0.097471,True
13,666082916733198337,https://pbs.twimg.com/media/CT5m4VGWEAAtKc8.jpg,1,pug,0.489814,True,bull_mastiff,0.404722,True,French_bulldog,0.048960,True
14,666094000022159362,https://pbs.twimg.com/media/CT5w9gUW4AAsBNN.jpg,1,bloodhound,0.195217,True,German_shepherd,0.078260,True,malinois,0.075628,True
15,666099513787052032,https://pbs.twimg.com/media/CT51-JJUEAA6hV8.jpg,1,Lhasa,0.582330,True,Shih-Tzu,0.166192,True,Dandie_Dinmont,0.089688,True
16,666102155909144576,https://pbs.twimg.com/media/CT54YGiWUAEZnoK.jpg,1,English_setter,0.298617,True,Newfoundland,0.149842,True,borzoi,0.133649,True
17,666104133288665088,https://pbs.twimg.com/media/CT56LSZWoAAlJj2.jpg,1,hen,0.965932,False,cock,0.033919,False,partridge,0.000052,False
18,666268910803644416,https://pbs.twimg.com/media/CT8QCd1WEAADXws.jpg,1,desktop_computer,0.086502,False,desk,0.085547,False,bookcase,0.079480,False
19,666273097616637952,https://pbs.twimg.com/media/CT8T1mtUwAA3aqm.jpg,1,Italian_greyhound,0.176053,True,toy_terrier,0.111884,True,basenji,0.111152,True
20,666287406224695296,https://pbs.twimg.com/media/CT8g3BpUEAAuFjg.jpg,1,Maltese_dog,0.857531,True,toy_poodle,0.063064,True,miniature_poodle,0.025581,True
21,666293911632134144,https://pbs.twimg.com/media/CT8mx7KW4AEQu8N.jpg,1,three-toed_sloth,0.914671,False,otter,0.015250,False,great_grey_owl,0.013207,False
22,666337882303524864,https://pbs.twimg.com/media/CT9OwFIWEAMuRje.jpg,1,ox,0.416669,False,Newfoundland,0.278407,True,groenendael,0.102643,True
23,666345417576210432,https://pbs.twimg.com/media/CT9Vn7PWoAA_ZCM.jpg,1,golden_retriever,0.858744,True,Chesapeake_Bay_retriever,0.054787,True,Labrador_retriever,0.014241,True
24,666353288456101888,https://pbs.twimg.com/media/CT9cx0tUEAAhNN_.jpg,1,malamute,0.336874,True,Siberian_husky,0.147655,True,Eskimo_dog,0.093412,True
25,666362758909284353,https://pbs.twimg.com/media/CT9lXGsUcAAyUFt.jpg,1,guinea_pig,0.996496,False,skunk,0.002402,False,hamster,0.000461,False
26,666373753744588802,https://pbs.twimg.com/media/CT9vZEYWUAAlZ05.jpg,1,soft-coated_wheaten_terrier,0.326467,True,Afghan_hound,0.259551,True,briard,0.206803,True
27,666396247373291520,https://pbs.twimg.com/media/CT-D2ZHWIAA3gK1.jpg,1,Chihuahua,0.978108,True,toy_terrier,0.009397,True,papillon,0.004577,True
28,666407126856765440,https://pbs.twimg.com/media/CT-NvwmW4AAugGZ.jpg,1,black-and-tan_coonhound,0.529139,True,bloodhound,0.244220,True,flat-coated_retriever,0.173810,True
29,666411507551481857,https://pbs.twimg.com/media/CT-RugiWIAELEaq.jpg,1,coho,0.404640,False,barracouta,0.271485,False,gar,0.189945,False
...,...,...,...,...,...,...,...,...,...,...,...,...
2045,886366144734445568,https://pbs.twimg.com/media/DE0BTnQUwAApKEH.jpg,1,French_bulldog,0.999201,True,Chihuahua,0.000361,True,Boston_bull,0.000076,True
2046,886680336477933568,https://pbs.twimg.com/media/DE4fEDzWAAAyHMM.jpg,1,convertible,0.738995,False,sports_car,0.139952,False,car_wheel,0.044173,False
2047,886736880519319552,https://pbs.twimg.com/media/DE5Se8FXcAAJFx4.jpg,1,kuvasz,0.309706,True,Great_Pyrenees,0.186136,True,Dandie_Dinmont,0.086346,True
2048,886983233522544640,https://pbs.twimg.com/media/DE8yicJW0AAAvBJ.jpg,2,Chihuahua,0.793469,True,toy_terrier,0.143528,True,can_opener,0.032253,False
2049,887101392804085760,https://pbs.twimg.com/media/DE-eAq6UwAA-jaE.jpg,1,Samoyed,0.733942,True,Eskimo_dog,0.035029,True,Staffordshire_bullterrier,0.029705,True
2050,887343217045368832,https://pbs.twimg.com/ext_tw_video_thumb/88734...,1,Mexican_hairless,0.330741,True,sea_lion,0.275645,False,Weimaraner,0.134203,True
2051,887473957103951883,https://pbs.twimg.com/media/DFDw2tyUQAAAFke.jpg,2,Pembroke,0.809197,True,Rhodesian_ridgeback,0.054950,True,beagle,0.038915,True
2052,887517139158093824,https://pbs.twimg.com/ext_tw_video_thumb/88751...,1,limousine,0.130432,False,tow_truck,0.029175,False,shopping_cart,0.026321,False
2053,887705289381826560,https://pbs.twimg.com/media/DFHDQBbXgAEqY7t.jpg,1,basset,0.821664,True,redbone,0.087582,True,Weimaraner,0.026236,True
2054,888078434458587136,https://pbs.twimg.com/media/DFMWn56WsAAkA7B.jpg,1,French_bulldog,0.995026,True,pug,0.000932,True,bull_mastiff,0.000903,True
2055,888202515573088257,https://pbs.twimg.com/media/DFDw2tyUQAAAFke.jpg,2,Pembroke,0.809197,True,Rhodesian_ridgeback,0.054950,True,beagle,0.038915,True
2056,888554962724278272,https://pbs.twimg.com/media/DFTH_O-UQAACu20.jpg,3,Siberian_husky,0.700377,True,Eskimo_dog,0.166511,True,malamute,0.111411,True
2057,888804989199671297,https://pbs.twimg.com/media/DFWra-3VYAA2piG.jpg,1,golden_retriever,0.469760,True,Labrador_retriever,0.184172,True,English_setter,0.073482,True
2058,888917238123831296,https://pbs.twimg.com/media/DFYRgsOUQAARGhO.jpg,1,golden_retriever,0.714719,True,Tibetan_mastiff,0.120184,True,Labrador_retriever,0.105506,True
2059,889278841981685760,https://pbs.twimg.com/ext_tw_video_thumb/88927...,1,whippet,0.626152,True,borzoi,0.194742,True,Saluki,0.027351,True
2060,889531135344209921,https://pbs.twimg.com/media/DFg_2PVW0AEHN3p.jpg,1,golden_retriever,0.953442,True,Labrador_retriever,0.013834,True,redbone,0.007958,True
2061,889638837579907072,https://pbs.twimg.com/media/DFihzFfXsAYGDPR.jpg,1,French_bulldog,0.991650,True,boxer,0.002129,True,Staffordshire_bullterrier,0.001498,True
2062,889665388333682689,https://pbs.twimg.com/media/DFi579UWsAAatzw.jpg,1,Pembroke,0.966327,True,Cardigan,0.027356,True,basenji,0.004633,True
2063,889880896479866881,https://pbs.twimg.com/media/DFl99B1WsAITKsg.jpg,1,French_bulldog,0.377417,True,Labrador_retriever,0.151317,True,muzzle,0.082981,False
2064,890006608113172480,https://pbs.twimg.com/media/DFnwSY4WAAAMliS.jpg,1,Samoyed,0.957979,True,Pomeranian,0.013884,True,chow,0.008167,True
2065,890240255349198849,https://pbs.twimg.com/media/DFrEyVuW0AAO3t9.jpg,1,Pembroke,0.511319,True,Cardigan,0.451038,True,Chihuahua,0.029248,True
2066,890609185150312448,https://pbs.twimg.com/media/DFwUU__XcAEpyXI.jpg,1,Irish_terrier,0.487574,True,Irish_setter,0.193054,True,Chesapeake_Bay_retriever,0.118184,True
2067,890729181411237888,https://pbs.twimg.com/media/DFyBahAVwAAhUTd.jpg,2,Pomeranian,0.566142,True,Eskimo_dog,0.178406,True,Pembroke,0.076507,True
2068,890971913173991426,https://pbs.twimg.com/media/DF1eOmZXUAALUcq.jpg,1,Appenzeller,0.341703,True,Border_collie,0.199287,True,ice_lolly,0.193548,False
2069,891087950875897856,https://pbs.twimg.com/media/DF3HwyEWsAABqE6.jpg,1,Chesapeake_Bay_retriever,0.425595,True,Irish_terrier,0.116317,True,Indian_elephant,0.076902,False
2070,891327558926688256,https://pbs.twimg.com/media/DF6hr6BUMAAzZgT.jpg,2,basset,0.555712,True,English_springer,0.225770,True,German_short-haired_pointer,0.175219,True
2071,891689557279858688,https://pbs.twimg.com/media/DF_q7IAWsAEuuN8.jpg,1,paper_towel,0.170278,False,Labrador_retriever,0.168086,True,spatula,0.040836,False
2072,891815181378084864,https://pbs.twimg.com/media/DGBdLU1WsAANxJ9.jpg,1,Chihuahua,0.716012,True,malamute,0.078253,True,kelpie,0.031379,True
2073,892177421306343426,https://pbs.twimg.com/media/DGGmoV4XsAAUL6n.jpg,1,Chihuahua,0.323581,True,Pekinese,0.090647,True,papillon,0.068957,True
2074,892420643555336193,https://pbs.twimg.com/media/DGKD1-bXoAAIAUK.jpg,1,orange,0.097049,False,bagel,0.085851,False,banana,0.076110,False

In [15]:
image_predictions.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2075 entries, 0 to 2074
Data columns (total 12 columns):
tweet_id    2075 non-null int64
jpg_url     2075 non-null object
img_num     2075 non-null int64
p1          2075 non-null object
p1_conf     2075 non-null float64
p1_dog      2075 non-null bool
p2          2075 non-null object
p2_conf     2075 non-null float64
p2_dog      2075 non-null bool
p3          2075 non-null object
p3_conf     2075 non-null float64
p3_dog      2075 non-null bool
dtypes: bool(3), float64(3), int64(2), object(4)
memory usage: 152.1+ KB

In [16]:
sum(image_predictions.jpg_url.duplicated())

66

In [19]:
print(image_predictions.p1_dog.value_counts())
print(image_predictions.p2_dog.value_counts())
print(image_predictions.p3_dog.value_counts())

True     1532
False     543
Name: p1_dog, dtype: int64
True     1553
False     522
Name: p2_dog, dtype: int64
True     1499
False     576
Name: p3_dog, dtype: int64

In [17]:
tweet_df

                tweet_id  favorite_count  retweet_count
0     892420643555336193           36321           7729
1     892177421306343426           31311           5723
2     891815181378084864           23583           3786
3     891689557279858688           39633           7894
4     891327558926688256           37828           8514
5     891087950875897856           19061           2850
6     890971913173991426           11101           1855
7     890729181411237888           61209          17252
8     890609185150312448           26223           3927
9     890240255349198849           29966           6720
10    890006608113172480           28855           6709
11    889880896479866881           26225           4565
12    889665388333682689           45187           9157
13    889638837579907072           25434           4109
14    889531135344209921           14223           2059
15    889278841981685760           23700           4876
16    888917238123831296           27381           4118
17    888804989199671297           24067           3882
18    888554962724278272           18586           3185
19    888078434458587136           20491           3168
20    887705289381826560           28440           4926
21    887517139158093824           43638          10775
22    887473957103951883           64690          16476
23    887343217045368832           31661           9575
24    887101392804085760           28794           5450
25    886983233522544640           32890           7018
26    886736880519319552           11277           2939
27    886680336477933568           21138           4086
28    886366144734445568           19898           2897
29    886267009285017600             112              4
...                  ...             ...            ...
2301  666411507551481857             413            301
2302  666407126856765440             100             32
2303  666396247373291520             159             76
2304  666373753744588802             174             85
2305  666362758909284353             728            521
2306  666353288456101888             199             66
2307  666345417576210432             274            128
2308  666337882303524864             182             84
2309  666293911632134144             469            321
2310  666287406224695296             138             62
2311  666273097616637952             161             73
2312  666268910803644416              96             32
2313  666104133288665088           13703           6006
2314  666102155909144576              72             11
2315  666099513787052032             143             60
2316  666094000022159362             154             67
2317  666082916733198337             103             41
2318  666073100786774016             297            147
2319  666071193221509120             136             53
2320  666063827256086533             449            198
2321  666058600524156928             105             54
2322  666057090499244032             270            127
2323  666055525042405380             410            221
2324  666051853826850816            1128            780
2325  666050758794694657             124             51
2326  666049248165822465              96             40
2327  666044226329800704             272            132
2328  666033412701032449             112             41
2329  666029285002620928             121             42
2330  666020888022790149            2422            463

[2331 rows x 3 columns]

In [18]:
sum(tweet_df.tweet_id.duplicated())

0

### Qulity Issues
`twitter_archive` columns:

- **Completeness:** 
    - in_reply_to_status_id, in_reply_to_user_id, retweeted_status_id, retweeted_status_user_id, retweeted_status_timestamp, expanded_urls have missing data on those columns.
- **Validity:** 
    - Some rating numbers in rating_number column are too large comparing to other rating number, such as 666; Some rating number is less than 10 which is not compliant to the rule.
    - Some denominator have invalid values.
- **Accuracy:**
    - retweeted_status_timestamp, timestamp should be datetime instead of object (string).
    - Name column have invalid names i.e 'None', 'a', 'an' and less than 3 characters.\
 
`image_predictions` columns:

- **Validity:**
    - Data in p1, p2, p3 have invalid infomation such as orange, bagel, and banana.
    - some tweets_ids have the same jpg_url
- **Consistency:** 
    - Some breeds are listed in lowercase, while sometimes it is written in Sentence case.
- **Completeness**
    - Missing values from images dataset, 2075 rows instead of 2356 rows in twitter_archive dataset.
    
`tweet_df` columns:
- **Completeness**
    - Missing some data, 2331 rows instead of 2356 rows.

### Tidiness Issues

- **twitter_archive:**
    - dogoo, floofer, pupper, puppo all related to the same variables.

- **image_predictions & tweet_df:**
    - Those two data sets are part of the same obervaional unit as the dataset in twitter_archive. Should be constructed in one table.

# Clean Data

In [147]:
twitter_archive_clean = twitter_archive.copy()
image_predictions_clean= image_predictions.copy()
tweet_df_clean = tweet_df.copy()

##### Define
- 1. Concatenate tweet_df and image_prediction to twitter_archive

##### Code

In [148]:
# Check how many different twitter_id
twitter_archive_clean.shape

(2356, 17)

In [149]:
twitter_archive_clean.head()

,tweet_id,in_reply_to_status_id,in_reply_to_user_id,timestamp,source,text,retweeted_status_id,retweeted_status_user_id,retweeted_status_timestamp,expanded_urls,rating_numerator,rating_denominator,name,doggo,floofer,pupper,puppo
0,892420643555336193,NaN,NaN,2017-08-01 16:23:56 +0000,"<a href=""http://twitter.com/download/iphone"" r...",This is Phineas. He's a mystical boy. Only eve...,NaN,NaN,NaN,https://twitter.com/dog_rates/status/892420643...,13,10,Phineas,None,None,None,None
1,892177421306343426,NaN,NaN,2017-08-01 00:17:27 +0000,"<a href=""http://twitter.com/download/iphone"" r...",This is Tilly. She's just checking pup on you....,NaN,NaN,NaN,https://twitter.com/dog_rates/status/892177421...,13,10,Tilly,None,None,None,None
2,891815181378084864,NaN,NaN,2017-07-31 00:18:03 +0000,"<a href=""http://twitter.com/download/iphone"" r...",This is Archie. He is a rare Norwegian Pouncin...,NaN,NaN,NaN,https://twitter.com/dog_rates/status/891815181...,12,10,Archie,None,None,None,None
3,891689557279858688,NaN,NaN,2017-07-30 15:58:51 +0000,"<a href=""http://twitter.com/download/iphone"" r...",This is Darla. She commenced a snooze mid meal...,NaN,NaN,NaN,https://twitter.com/dog_rates/status/891689557...,13,10,Darla,None,None,None,None
4,891327558926688256,NaN,NaN,2017-07-29 16:00:24 +0000,"<a href=""http://twitter.com/download/iphone"" r...",This is Franklin. He would like you to stop ca...,NaN,NaN,NaN,https://twitter.com/dog_rates/status/891327558...,12,10,Franklin,None,None,None,None

In [150]:
sum(twitter_archive_clean.tweet_id.duplicated())

0

In [151]:
image_predictions_clean.shape

(2075, 12)

In [152]:
image_predictions_clean.head()

,tweet_id,jpg_url,img_num,p1,p1_conf,p1_dog,p2,p2_conf,p2_dog,p3,p3_conf,p3_dog
0,666020888022790149,https://pbs.twimg.com/media/CT4udn0WwAA0aMy.jpg,1,Welsh_springer_spaniel,0.465074,True,collie,0.156665,True,Shetland_sheepdog,0.061428,True
1,666029285002620928,https://pbs.twimg.com/media/CT42GRgUYAA5iDo.jpg,1,redbone,0.506826,True,miniature_pinscher,0.074192,True,Rhodesian_ridgeback,0.072010,True
2,666033412701032449,https://pbs.twimg.com/media/CT4521TWwAEvMyu.jpg,1,German_shepherd,0.596461,True,malinois,0.138584,True,bloodhound,0.116197,True
3,666044226329800704,https://pbs.twimg.com/media/CT5Dr8HUEAA-lEu.jpg,1,Rhodesian_ridgeback,0.408143,True,redbone,0.360687,True,miniature_pinscher,0.222752,True
4,666049248165822465,https://pbs.twimg.com/media/CT5IQmsXIAAKY4A.jpg,1,miniature_pinscher,0.560311,True,Rottweiler,0.243682,True,Doberman,0.154629,True

In [153]:
sum(image_predictions_clean.tweet_id.duplicated())

0

In [154]:
tweet_df_clean.shape

(2331, 3)

In [155]:
sum(tweet_df_clean.tweet_id.duplicated())

0

In [156]:
dog_rate = pd.merge(twitter_archive_clean, image_predictions_clean, on = 'tweet_id')

In [157]:
dog_rate = pd.merge(dog_rate, tweet_df_clean, on = 'tweet_id')

##### Test

In [158]:
dog_rate.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 2059 entries, 0 to 2058
Data columns (total 30 columns):
tweet_id                      2059 non-null int64
in_reply_to_status_id         23 non-null float64
in_reply_to_user_id           23 non-null float64
timestamp                     2059 non-null object
source                        2059 non-null object
text                          2059 non-null object
retweeted_status_id           72 non-null float64
retweeted_status_user_id      72 non-null float64
retweeted_status_timestamp    72 non-null object
expanded_urls                 2059 non-null object
rating_numerator              2059 non-null int64
rating_denominator            2059 non-null int64
name                          2059 non-null object
doggo                         2059 non-null object
floofer                       2059 non-null object
pupper                        2059 non-null object
puppo                         2059 non-null object
jpg_url                       2059 non-null object
img_num                       2059 non-null int64
p1                            2059 non-null object
p1_conf                       2059 non-null float64
p1_dog                        2059 non-null bool
p2                            2059 non-null object
p2_conf                       2059 non-null float64
p2_dog                        2059 non-null bool
p3                            2059 non-null object
p3_conf                       2059 non-null float64
p3_dog                        2059 non-null bool
favorite_count                2059 non-null int64
retweet_count                 2059 non-null int64
dtypes: bool(3), float64(7), int64(6), object(14)
memory usage: 456.4+ KB

#### Define

- 2. Melt the 'doggo', 'loofer', 'pupper' and 'puppo' into one column called dog_breed.

#### Code

In [159]:
dog_rate.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 2059 entries, 0 to 2058
Data columns (total 30 columns):
tweet_id                      2059 non-null int64
in_reply_to_status_id         23 non-null float64
in_reply_to_user_id           23 non-null float64
timestamp                     2059 non-null object
source                        2059 non-null object
text                          2059 non-null object
retweeted_status_id           72 non-null float64
retweeted_status_user_id      72 non-null float64
retweeted_status_timestamp    72 non-null object
expanded_urls                 2059 non-null object
rating_numerator              2059 non-null int64
rating_denominator            2059 non-null int64
name                          2059 non-null object
doggo                         2059 non-null object
floofer                       2059 non-null object
pupper                        2059 non-null object
puppo                         2059 non-null object
jpg_url                       2059 non-null object
img_num                       2059 non-null int64
p1                            2059 non-null object
p1_conf                       2059 non-null float64
p1_dog                        2059 non-null bool
p2                            2059 non-null object
p2_conf                       2059 non-null float64
p2_dog                        2059 non-null bool
p3                            2059 non-null object
p3_conf                       2059 non-null float64
p3_dog                        2059 non-null bool
favorite_count                2059 non-null int64
retweet_count                 2059 non-null int64
dtypes: bool(3), float64(7), int64(6), object(14)
memory usage: 456.4+ KB

In [160]:
MELTS_COLUMNS = ['doggo', 'floofer', 'pupper', 'puppo']
STAY_COLUMNS = [x for x in dog_rate.columns.tolist() if x not in MELTS_COLUMNS]


# Melt the the columns into values
dog_rate = pd.melt(dog_rate, id_vars = STAY_COLUMNS, value_vars = MELTS_COLUMNS, 
                         var_name = 'stages', value_name = 'dog_stage')
# Delete column 'stages'
dog_rate = dog_rate.drop('stages', axis= 1)

In [161]:
dog_rate = dog_rate.drop_duplicates()

#### Test

In [162]:
dog_rate.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 2390 entries, 0 to 7053
Data columns (total 27 columns):
tweet_id                      2390 non-null int64
in_reply_to_status_id         27 non-null float64
in_reply_to_user_id           27 non-null float64
timestamp                     2390 non-null object
source                        2390 non-null object
text                          2390 non-null object
retweeted_status_id           87 non-null float64
retweeted_status_user_id      87 non-null float64
retweeted_status_timestamp    87 non-null object
expanded_urls                 2390 non-null object
rating_numerator              2390 non-null int64
rating_denominator            2390 non-null int64
name                          2390 non-null object
jpg_url                       2390 non-null object
img_num                       2390 non-null int64
p1                            2390 non-null object
p1_conf                       2390 non-null float64
p1_dog                        2390 non-null bool
p2                            2390 non-null object
p2_conf                       2390 non-null float64
p2_dog                        2390 non-null bool
p3                            2390 non-null object
p3_conf                       2390 non-null float64
p3_dog                        2390 non-null bool
favorite_count                2390 non-null int64
retweet_count                 2390 non-null int64
dog_stage                     2390 non-null object
dtypes: bool(3), float64(7), int64(6), object(11)
memory usage: 473.8+ KB

In [163]:
dog_rate.dog_stage.value_counts()

None       2059
pupper      221
doggo        78
puppo        24
floofer       8
Name: dog_stage, dtype: int64

#### Define

- 3.Delete the columns and rows that is invalid or not needed anymore.

In [164]:
dog_rate.head()

,tweet_id,in_reply_to_status_id,in_reply_to_user_id,timestamp,source,text,retweeted_status_id,retweeted_status_user_id,retweeted_status_timestamp,expanded_urls,...,p1_dog,p2,p2_conf,p2_dog,p3,p3_conf,p3_dog,favorite_count,retweet_count,dog_stage
0,892420643555336193,NaN,NaN,2017-08-01 16:23:56 +0000,"<a href=""http://twitter.com/download/iphone"" r...",This is Phineas. He's a mystical boy. Only eve...,NaN,NaN,NaN,https://twitter.com/dog_rates/status/892420643...,...,False,bagel,0.085851,False,banana,0.076110,False,36321,7729,None
1,892177421306343426,NaN,NaN,2017-08-01 00:17:27 +0000,"<a href=""http://twitter.com/download/iphone"" r...",This is Tilly. She's just checking pup on you....,NaN,NaN,NaN,https://twitter.com/dog_rates/status/892177421...,...,True,Pekinese,0.090647,True,papillon,0.068957,True,31311,5723,None
2,891815181378084864,NaN,NaN,2017-07-31 00:18:03 +0000,"<a href=""http://twitter.com/download/iphone"" r...",This is Archie. He is a rare Norwegian Pouncin...,NaN,NaN,NaN,https://twitter.com/dog_rates/status/891815181...,...,True,malamute,0.078253,True,kelpie,0.031379,True,23583,3786,None
3,891689557279858688,NaN,NaN,2017-07-30 15:58:51 +0000,"<a href=""http://twitter.com/download/iphone"" r...",This is Darla. She commenced a snooze mid meal...,NaN,NaN,NaN,https://twitter.com/dog_rates/status/891689557...,...,False,Labrador_retriever,0.168086,True,spatula,0.040836,False,39633,7894,None
4,891327558926688256,NaN,NaN,2017-07-29 16:00:24 +0000,"<a href=""http://twitter.com/download/iphone"" r...",This is Franklin. He would like you to stop ca...,NaN,NaN,NaN,https://twitter.com/dog_rates/status/891327558...,...,True,English_springer,0.225770,True,German_short-haired_pointer,0.175219,True,37828,8514,None

In [165]:
# Keep the rows
dog_rate = dog_rate[np.isnan(dog_rate.retweeted_status_id)]

In [166]:
dog_rate.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 2303 entries, 0 to 7053
Data columns (total 27 columns):
tweet_id                      2303 non-null int64
in_reply_to_status_id         27 non-null float64
in_reply_to_user_id           27 non-null float64
timestamp                     2303 non-null object
source                        2303 non-null object
text                          2303 non-null object
retweeted_status_id           0 non-null float64
retweeted_status_user_id      0 non-null float64
retweeted_status_timestamp    0 non-null object
expanded_urls                 2303 non-null object
rating_numerator              2303 non-null int64
rating_denominator            2303 non-null int64
name                          2303 non-null object
jpg_url                       2303 non-null object
img_num                       2303 non-null int64
p1                            2303 non-null object
p1_conf                       2303 non-null float64
p1_dog                        2303 non-null bool
p2                            2303 non-null object
p2_conf                       2303 non-null float64
p2_dog                        2303 non-null bool
p3                            2303 non-null object
p3_conf                       2303 non-null float64
p3_dog                        2303 non-null bool
favorite_count                2303 non-null int64
retweet_count                 2303 non-null int64
dog_stage                     2303 non-null object
dtypes: bool(3), float64(7), int64(6), object(11)
memory usage: 456.6+ KB

In [167]:
# Drop the following columns
dog_rate = dog_rate.drop(['retweeted_status_id', 'retweeted_status_user_id', 'retweeted_status_timestamp'], axis=1)

In [168]:
dog_rate.head()

,tweet_id,in_reply_to_status_id,in_reply_to_user_id,timestamp,source,text,expanded_urls,rating_numerator,rating_denominator,name,...,p1_dog,p2,p2_conf,p2_dog,p3,p3_conf,p3_dog,favorite_count,retweet_count,dog_stage
0,892420643555336193,NaN,NaN,2017-08-01 16:23:56 +0000,"<a href=""http://twitter.com/download/iphone"" r...",This is Phineas. He's a mystical boy. Only eve...,https://twitter.com/dog_rates/status/892420643...,13,10,Phineas,...,False,bagel,0.085851,False,banana,0.076110,False,36321,7729,None
1,892177421306343426,NaN,NaN,2017-08-01 00:17:27 +0000,"<a href=""http://twitter.com/download/iphone"" r...",This is Tilly. She's just checking pup on you....,https://twitter.com/dog_rates/status/892177421...,13,10,Tilly,...,True,Pekinese,0.090647,True,papillon,0.068957,True,31311,5723,None
2,891815181378084864,NaN,NaN,2017-07-31 00:18:03 +0000,"<a href=""http://twitter.com/download/iphone"" r...",This is Archie. He is a rare Norwegian Pouncin...,https://twitter.com/dog_rates/status/891815181...,12,10,Archie,...,True,malamute,0.078253,True,kelpie,0.031379,True,23583,3786,None
3,891689557279858688,NaN,NaN,2017-07-30 15:58:51 +0000,"<a href=""http://twitter.com/download/iphone"" r...",This is Darla. She commenced a snooze mid meal...,https://twitter.com/dog_rates/status/891689557...,13,10,Darla,...,False,Labrador_retriever,0.168086,True,spatula,0.040836,False,39633,7894,None
4,891327558926688256,NaN,NaN,2017-07-29 16:00:24 +0000,"<a href=""http://twitter.com/download/iphone"" r...",This is Franklin. He would like you to stop ca...,https://twitter.com/dog_rates/status/891327558...,12,10,Franklin,...,True,English_springer,0.225770,True,German_short-haired_pointer,0.175219,True,37828,8514,None

In [169]:
# Drop columns that is no longer needed
dog_rate.drop(['in_reply_to_status_id', 
                  'in_reply_to_user_id',
                  'source',
                  'img_num'], axis = 1, inplace=True)

#### Test

In [170]:
dog_rate.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 2303 entries, 0 to 7053
Data columns (total 20 columns):
tweet_id              2303 non-null int64
timestamp             2303 non-null object
text                  2303 non-null object
expanded_urls         2303 non-null object
rating_numerator      2303 non-null int64
rating_denominator    2303 non-null int64
name                  2303 non-null object
jpg_url               2303 non-null object
p1                    2303 non-null object
p1_conf               2303 non-null float64
p1_dog                2303 non-null bool
p2                    2303 non-null object
p2_conf               2303 non-null float64
p2_dog                2303 non-null bool
p3                    2303 non-null object
p3_conf               2303 non-null float64
p3_dog                2303 non-null bool
favorite_count        2303 non-null int64
retweet_count         2303 non-null int64
dog_stage             2303 non-null object
dtypes: bool(3), float64(3), int64(5), object(9)
memory usage: 330.6+ KB

#### Define

- 4. Change tweet_id from an integer to a string.
- 5. Change Timestamps to datetime format.

In [171]:
dog_rate.tweet_id = dog_rate.tweet_id.astype(str)

In [172]:
dog_rate['timestamp'] = dog_rate['timestamp'].str.slice(start=0, stop=-6)

In [173]:
dog_rate.timestamp

0       2017-08-01 16:23:56
1       2017-08-01 00:17:27
2       2017-07-31 00:18:03
3       2017-07-30 15:58:51
4       2017-07-29 16:00:24
5       2017-07-29 00:08:17
6       2017-07-28 16:27:12
7       2017-07-28 00:22:40
8       2017-07-27 16:25:51
9       2017-07-26 15:59:51
10      2017-07-26 00:31:25
11      2017-07-25 16:11:53
12      2017-07-25 01:55:32
13      2017-07-25 00:10:02
14      2017-07-24 17:02:04
15      2017-07-24 00:19:32
16      2017-07-23 00:22:39
17      2017-07-22 16:56:37
18      2017-07-22 00:23:06
19      2017-07-20 16:49:33
20      2017-07-19 16:06:48
21      2017-07-19 03:39:09
22      2017-07-19 00:47:34
23      2017-07-18 16:08:03
24      2017-07-18 00:07:08
25      2017-07-17 16:17:36
26      2017-07-16 23:58:41
27      2017-07-16 20:14:00
28      2017-07-15 23:25:31
29      2017-07-15 16:17:19
               ...
5817    2015-12-04 03:43:54
5818    2015-12-04 03:13:46
5821    2015-12-04 01:55:13
5828    2015-12-03 18:23:34
5835    2015-12-03 03:21:00
5841    2015-12-03 00:07:09
5843    2015-12-02 21:06:56
6189    2017-07-25 01:55:32
6191    2017-07-24 17:02:04
6240    2017-06-25 00:45:22
6257    2017-06-11 21:18:31
6283    2017-05-24 16:44:18
6314    2017-05-03 03:17:27
6328    2017-04-22 18:31:02
6483    2017-01-29 02:44:34
6485    2017-01-27 17:04:02
6497    2017-01-21 18:26:02
6517    2017-01-13 17:00:21
6616    2016-11-30 01:31:12
6626    2016-11-25 19:55:35
6685    2016-10-31 21:00:23
6701    2016-10-25 16:00:09
6721    2016-10-16 18:11:26
6759    2016-09-28 00:46:20
6918    2016-07-21 23:53:04
6937    2016-07-11 15:07:30
6949    2016-07-07 19:16:47
7011    2016-06-20 20:49:19
7022    2016-06-16 01:25:36
7053    2016-06-03 01:07:16
Name: timestamp, Length: 2303, dtype: object

In [174]:
dog_rate.timestamp = pd.to_datetime(dog_rate.timestamp)

#### Test

In [175]:
dog_rate.head()

,tweet_id,timestamp,text,expanded_urls,rating_numerator,rating_denominator,name,jpg_url,p1,p1_conf,p1_dog,p2,p2_conf,p2_dog,p3,p3_conf,p3_dog,favorite_count,retweet_count,dog_stage
0,892420643555336193,2017-08-01 16:23:56,This is Phineas. He's a mystical boy. Only eve...,https://twitter.com/dog_rates/status/892420643...,13,10,Phineas,https://pbs.twimg.com/media/DGKD1-bXoAAIAUK.jpg,orange,0.097049,False,bagel,0.085851,False,banana,0.076110,False,36321,7729,None
1,892177421306343426,2017-08-01 00:17:27,This is Tilly. She's just checking pup on you....,https://twitter.com/dog_rates/status/892177421...,13,10,Tilly,https://pbs.twimg.com/media/DGGmoV4XsAAUL6n.jpg,Chihuahua,0.323581,True,Pekinese,0.090647,True,papillon,0.068957,True,31311,5723,None
2,891815181378084864,2017-07-31 00:18:03,This is Archie. He is a rare Norwegian Pouncin...,https://twitter.com/dog_rates/status/891815181...,12,10,Archie,https://pbs.twimg.com/media/DGBdLU1WsAANxJ9.jpg,Chihuahua,0.716012,True,malamute,0.078253,True,kelpie,0.031379,True,23583,3786,None
3,891689557279858688,2017-07-30 15:58:51,This is Darla. She commenced a snooze mid meal...,https://twitter.com/dog_rates/status/891689557...,13,10,Darla,https://pbs.twimg.com/media/DF_q7IAWsAEuuN8.jpg,paper_towel,0.170278,False,Labrador_retriever,0.168086,True,spatula,0.040836,False,39633,7894,None
4,891327558926688256,2017-07-29 16:00:24,This is Franklin. He would like you to stop ca...,https://twitter.com/dog_rates/status/891327558...,12,10,Franklin,https://pbs.twimg.com/media/DF6hr6BUMAAzZgT.jpg,basset,0.555712,True,English_springer,0.225770,True,German_short-haired_pointer,0.175219,True,37828,8514,None

#### Define

- 6. Remove or modify the observation with invalid denominator.
- 7. Correct naming issues.

#### Code

In [176]:
dog_rate.rating_denominator.value_counts()

10     2285
50        3
11        2
80        2
7         1
170       1
150       1
130       1
120       1
110       1
90        1
70        1
40        1
20        1
2         1
Name: rating_denominator, dtype: int64

In [177]:
dog_rate = dog_rate[dog_rate.rating_denominator == 10]

In [178]:
dog_rate.name.value_counts()

None         657
a             58
Cooper        13
Oliver        12
Charlie       11
Lucy          10
Winston        9
the            9
Penny          9
Tucker         9
Bo             8
Sadie          8
Lola           7
Jax            7
Daisy          7
Toby           7
Milo           7
Bella          7
Koda           6
just           6
one            6
Scout          6
Stanley        6
Gus            6
Maggie         6
Chester        5
Dave           5
Buddy          5
Sophie         5
Scooter        5
            ...
Lacy           1
Cora           1
Tater          1
Fred           1
Furzey         1
Ralpher        1
Stephanus      1
Loomis         1
Jeffrie        1
Patch          1
Bookstore      1
Tobi           1
Carter         1
Skittles       1
Reagan         1
Dotsy          1
Ralf           1
Swagger        1
Lance          1
Kody           1
Chadrick       1
Butter         1
Spanky         1
Huxley         1
Jersey         1
Tuck           1
Evy            1
Boots          1
Liam           1
Emma           1
Name: name, Length: 931, dtype: int64

In [179]:
dog_rate.name = dog_rate.name.str.replace('^[a-z]+','None')

#### Test

In [180]:
dog_rate.rating_denominator.value_counts()

10    2285
Name: rating_denominator, dtype: int64

In [181]:
dog_rate.name.sample(5)

5308        None
5437        None
1542        Duke
951     Reginald
851         Phil
Name: name, dtype: object

#### Define

- 8. Get rid of image prediction columns.

In [182]:
# We will store the fisrt true algorithm with it's level of confidence
prediction_algorithm = []
confidence_level = []

# Get_prediction_confidence function:
# search the first true algorithm and append it to a list with it's level of confidence
# if flase prediction_algorthm will have a value of NaN
def get_prediction_confidence(dataframe):
    if dataframe['p1_dog'] == True:
        prediction_algorithm.append(dataframe['p1'])
        confidence_level.append(dataframe['p1_conf'])
    elif dataframe['p2_dog'] == True:
        prediction_algorithm.append(dataframe['p2'])
        confidence_level.append(dataframe['p2_conf'])
    elif dataframe['p3_dog'] == True:
        prediction_algorithm.append(dataframe['p3'])
        confidence_level.append(dataframe['p3_conf'])
    else:
        prediction_algorithm.append('NaN')
        confidence_level.append(0)

dog_rate.apply(get_prediction_confidence, axis=1)
dog_rate['prediction_algorithm'] = prediction_algorithm
dog_rate['confidence_level'] = confidence_level

In [183]:
list(dog_rate)

['tweet_id',
 'timestamp',
 'text',
 'expanded_urls',
 'rating_numerator',
 'rating_denominator',
 'name',
 'jpg_url',
 'p1',
 'p1_conf',
 'p1_dog',
 'p2',
 'p2_conf',
 'p2_dog',
 'p3',
 'p3_conf',
 'p3_dog',
 'favorite_count',
 'retweet_count',
 'dog_stage',
 'prediction_algorithm',
 'confidence_level']

In [184]:
dog_rate = dog_rate.drop(['p1', 'p1_conf', 'p1_dog', 'p2', 'p2_conf', 'p2_dog', 'p3', 'p3_conf', 'p3_dog'],axis = 1)

#### Test

In [185]:
dog_rate.head()

,tweet_id,timestamp,text,expanded_urls,rating_numerator,rating_denominator,name,jpg_url,favorite_count,retweet_count,dog_stage,prediction_algorithm,confidence_level
0,892420643555336193,2017-08-01 16:23:56,This is Phineas. He's a mystical boy. Only eve...,https://twitter.com/dog_rates/status/892420643...,13,10,Phineas,https://pbs.twimg.com/media/DGKD1-bXoAAIAUK.jpg,36321,7729,None,NaN,0.000000
1,892177421306343426,2017-08-01 00:17:27,This is Tilly. She's just checking pup on you....,https://twitter.com/dog_rates/status/892177421...,13,10,Tilly,https://pbs.twimg.com/media/DGGmoV4XsAAUL6n.jpg,31311,5723,None,Chihuahua,0.323581
2,891815181378084864,2017-07-31 00:18:03,This is Archie. He is a rare Norwegian Pouncin...,https://twitter.com/dog_rates/status/891815181...,12,10,Archie,https://pbs.twimg.com/media/DGBdLU1WsAANxJ9.jpg,23583,3786,None,Chihuahua,0.716012
3,891689557279858688,2017-07-30 15:58:51,This is Darla. She commenced a snooze mid meal...,https://twitter.com/dog_rates/status/891689557...,13,10,Darla,https://pbs.twimg.com/media/DF_q7IAWsAEuuN8.jpg,39633,7894,None,Labrador_retriever,0.168086
4,891327558926688256,2017-07-29 16:00:24,This is Franklin. He would like you to stop ca...,https://twitter.com/dog_rates/status/891327558...,12,10,Franklin,https://pbs.twimg.com/media/DF6hr6BUMAAzZgT.jpg,37828,8514,None,basset,0.555712

In [186]:
dog_rate.prediction_algorithm.value_counts()

NaN                               354
golden_retriever                  192
Labrador_retriever                123
Pembroke                          108
Chihuahua                          99
pug                                73
toy_poodle                         58
Pomeranian                         53
chow                               50
Samoyed                            47
malamute                           36
cocker_spaniel                     35
Chesapeake_Bay_retriever           34
French_bulldog                     34
Eskimo_dog                         28
miniature_pinscher                 28
German_shepherd                    28
Lakeland_terrier                   24
Cardigan                           23
Shetland_sheepdog                  22
Siberian_husky                     22
Shih-Tzu                           22
Staffordshire_bullterrier          22
Rottweiler                         21
kuvasz                             21
beagle                             21
Italian_greyhound                  20
Maltese_dog                        20
basset                             19
American_Staffordshire_terrier     18
                                 ...
Leonberg                            4
Irish_water_spaniel                 4
Tibetan_terrier                     4
Gordon_setter                       4
Greater_Swiss_Mountain_dog          4
Scottish_deerhound                  4
Saluki                              4
komondor                            4
giant_schnauzer                     4
Brabancon_griffon                   4
Weimaraner                          4
Welsh_springer_spaniel              4
bluetick                            4
wire-haired_fox_terrier             3
Afghan_hound                        3
black-and-tan_coonhound             3
toy_terrier                         3
cairn                               3
clumber                             2
Australian_terrier                  2
Sussex_spaniel                      2
groenendael                         2
Appenzeller                         2
Bouvier_des_Flandres                1
standard_schnauzer                  1
Irish_wolfhound                     1
EntleBucher                         1
silky_terrier                       1
Japanese_spaniel                    1
Scotch_terrier                      1
Name: prediction_algorithm, Length: 114, dtype: int64

#### Define

- 9. Fix rating numerator and denominators that are invalid or incorrect values.

In [187]:
# View all occurences where there are more than one #/# in 'text' column
dog_rate_fix = dog_rate[dog_rate.text.str.contains( r"(\d+\.?\d*\/\d+\.?\d*\D+\d+\.?\d*\/\d+\.?\d*)")].text
dog_rate_fix

/opt/conda/lib/python3.6/site-packages/ipykernel_launcher.py:2: UserWarning: This pattern has match groups. To actually get the groups, use str.extract.

605     "Yep... just as I suspected. You're not flossi...
812     This is Bookstore and Seaweed. Bookstore is ti...
1004    Meet Travis and Flurp. Travis is pretty chill ...
1126    This is Socks. That water pup w the super legs...
1216    This may be the greatest video I've ever been ...
1221    Meet Oliviér. He takes killer selfies. Has a d...
1256    When bae says they can't go out but you see th...
1271    This is Eriq. His friend just reminded him of ...
1282    Meet Fynn &amp; Taco. Fynn is an all-powerful ...
1513    Meet Tassy &amp; Bee. Tassy is pretty chill, b...
1547    These two pups just met and have instantly bon...
1609    Meet Rufio. He is unaware of the pink legless ...
1613    Two gorgeous dogs here. Little waddling dog is...
1678    Meet Eve. She's a raging alcoholic 8/10 (would...
1718    10/10 for dog. 7/10 for cat. 12/10 for human. ...
1771    Meet Holly. She's trying to teach small human-...
1820    Meet Hank and Sully. Hank is very proud of the...
1883    Here we have Pancho and Peaches. Pancho is a C...
1920    This is Spark. He's nervous. Other dog hasn't ...
1967    This is Kial. Kial is either wearing a cape, w...
1976    Two dogs in this one. Both are rare Jujitsu Py...
2009    These are Peruvian Feldspars. Their names are ...
5727    Meet Rufio. He is unaware of the pink legless ...
5796    Meet Eve. She's a raging alcoholic 8/10 (would...
Name: text, dtype: object

In [188]:
import re
for entry in dog_rate_fix:
    mask = dog_rate.text == entry
    column_name1 = 'rating_numerator'
    column_name2 = 'rating_denominator'
    dog_rate.loc[mask, column_name1] = re.findall(r"\d+\.?\d*\/\d+\.?\d*\D+(\d+\.?\d*)\/\d+\.?\d*", entry)
    dog_rate.loc[mask, column_name2] = 10

#### Test

In [189]:
dog_rate[dog_rate.text.isin(dog_rate_fix)]

,tweet_id,timestamp,text,expanded_urls,rating_numerator,rating_denominator,name,jpg_url,favorite_count,retweet_count,dog_stage,prediction_algorithm,confidence_level
605,777684233540206592,2016-09-19 01:42:24,"""Yep... just as I suspected. You're not flossi...",https://twitter.com/dog_rates/status/777684233...,11,10,None,https://pbs.twimg.com/media/CsrjryzWgAAZY00.jpg,11435,2984,None,cocker_spaniel,0.253442
812,747600769478692864,2016-06-28 01:21:27,This is Bookstore and Seaweed. Bookstore is ti...,https://twitter.com/dog_rates/status/747600769...,7,10,Bookstore,https://pbs.twimg.com/media/CmAC7ehXEAAqSuW.jpg,2343,555,None,Chesapeake_Bay_retriever,0.804363
1004,714258258790387713,2016-03-28 01:10:13,Meet Travis and Flurp. Travis is pretty chill ...,https://twitter.com/dog_rates/status/714258258...,8,10,Travis,https://pbs.twimg.com/media/CemOGNjWQAEoN7R.jpg,3029,714,None,collie,0.176758
1126,703356393781329922,2016-02-26 23:10:06,This is Socks. That water pup w the super legs...,https://twitter.com/dog_rates/status/703356393...,2,10,Socks,https://pbs.twimg.com/media/CcLS6QKUcAAUuPa.jpg,1918,383,None,Border_collie,0.894842
1216,695064344191721472,2016-02-04 02:00:27,This may be the greatest video I've ever been ...,https://twitter.com/dog_rates/status/695064344...,13,10,None,https://pbs.twimg.com/ext_tw_video_thumb/69506...,1606,589,None,NaN,0.000000
1221,694352839993344000,2016-02-02 02:53:12,Meet Oliviér. He takes killer selfies. Has a d...,https://twitter.com/dog_rates/status/694352839...,5,10,Oliviér,https://pbs.twimg.com/media/CaLWOPfWkAAo2Dt.jpg,2041,615,None,Australian_terrier,0.407886
1256,691483041324204033,2016-01-25 04:49:38,When bae says they can't go out but you see th...,https://twitter.com/dog_rates/status/691483041...,10,10,None,https://pbs.twimg.com/media/CZikKBIWYAA40Az.jpg,2394,563,None,bloodhound,0.886232
1271,690400367696297985,2016-01-22 05:07:29,This is Eriq. His friend just reminded him of ...,https://twitter.com/dog_rates/status/690400367...,6,10,Eriq,https://pbs.twimg.com/media/CZTLeBuWIAAFkeR.jpg,1893,452,None,Pembroke,0.426459
1282,689835978131935233,2016-01-20 15:44:48,Meet Fynn &amp; Taco. Fynn is an all-powerful ...,https://twitter.com/dog_rates/status/689835978...,10,10,Fynn,https://pbs.twimg.com/media/CZLKJpDWQAA-5u4.jpg,2172,743,None,collie,0.600186
1513,677314812125323265,2015-12-17 02:30:09,"Meet Tassy &amp; Bee. Tassy is pretty chill, b...",https://twitter.com/dog_rates/status/677314812...,11,10,Tassy,https://pbs.twimg.com/media/CWZOOIUW4AAQrX_.jpg,1622,524,None,Blenheim_spaniel,0.924127
1547,676191832485810177,2015-12-14 00:07:50,These two pups just met and have instantly bon...,https://twitter.com/dog_rates/status/676191832...,7,10,None,https://pbs.twimg.com/media/CWJQ4UmWoAIJ29t.jpg,2242,1011,None,Chihuahua,0.376741
1609,674737130913071104,2015-12-09 23:47:22,Meet Rufio. He is unaware of the pink legless ...,https://twitter.com/dog_rates/status/674737130...,4,10,Rufio,https://pbs.twimg.com/media/CV0l10AU8AAfg-a.jpg,626,85,None,Pomeranian,0.948537
1613,674646392044941312,2015-12-09 17:46:48,Two gorgeous dogs here. Little waddling dog is...,https://twitter.com/dog_rates/status/674646392...,8,10,None,https://pbs.twimg.com/media/CVzTUGrW4AAirJH.jpg,1400,479,None,flat-coated_retriever,0.837448
1678,673295268553605120,2015-12-06 00:17:55,Meet Eve. She's a raging alcoholic 8/10 (would...,https://twitter.com/dog_rates/status/673295268...,11,10,Eve,https://pbs.twimg.com/media/CVgGc9hWIAIe1bn.jpg,7276,3062,None,golden_retriever,0.889241
1718,672248013293752320,2015-12-03 02:56:30,10/10 for dog. 7/10 for cat. 12/10 for human. ...,https://twitter.com/dog_rates/status/672248013...,7,10,None,https://pbs.twimg.com/media/CVROAIfWsAECA5t.jpg,1684,579,None,Irish_terrier,0.413173
1771,671154572044468225,2015-11-30 02:31:34,Meet Holly. She's trying to teach small human-...,https://twitter.com/dog_rates/status/671154572...,8,10,Holly,https://pbs.twimg.com/media/CVBrhXoWIAAox_C.jpg,687,209,None,Labrador_retriever,0.495047
1820,670434127938719744,2015-11-28 02:48:46,Meet Hank and Sully. Hank is very proud of the...,https://twitter.com/dog_rates/status/670434127...,8,10,Hank,https://pbs.twimg.com/media/CU3cSG8W4AIAePH.jpg,1358,619,None,Chesapeake_Bay_retriever,0.027351
1883,669037058363662336,2015-11-24 06:17:19,Here we have Pancho and Peaches. Pancho is a C...,https://twitter.com/dog_rates/status/669037058...,7,10,None,https://pbs.twimg.com/media/CUjlp51WcAA1vGA.jpg,632,299,None,Chihuahua,0.803528
1920,668537837512433665,2015-11-22 21:13:35,This is Spark. He's nervous. Other dog hasn't ...,https://twitter.com/dog_rates/status/668537837...,1,10,Spark,https://pbs.twimg.com/media/CUcfnWlWsAAzlwE.jpg,245,68,None,Lakeland_terrier,0.372988
1967,667544320556335104,2015-11-20 03:25:43,"This is Kial. Kial is either wearing a cape, w...",https://twitter.com/dog_rates/status/667544320...,4,10,Kial,https://pbs.twimg.com/media/CUOYBbbWIAAXQGU.jpg,828,501,None,Pomeranian,0.412893
1976,667491009379606528,2015-11-19 23:53:52,Two dogs in this one. Both are rare Jujitsu Py...,https://twitter.com/dog_rates/status/667491009...,8,10,None,https://pbs.twimg.com/media/CUNniSlUYAEj1Jl.jpg,513,213,None,borzoi,0.852088
2009,666835007768551424,2015-11-18 04:27:09,These are Peruvian Feldspars. Their names are ...,https://twitter.com/dog_rates/status/666835007...,10,10,None,https://pbs.twimg.com/media/CUES51dXIAEahyG.jpg,202,77,None,Airedale,0.448459
5727,674737130913071104,2015-12-09 23:47:22,Meet Rufio. He is unaware of the pink legless ...,https://twitter.com/dog_rates/status/674737130...,4,10,Rufio,https://pbs.twimg.com/media/CV0l10AU8AAfg-a.jpg,626,85,pupper,Pomeranian,0.948537
5796,673295268553605120,2015-12-06 00:17:55,Meet Eve. She's a raging alcoholic 8/10 (would...,https://twitter.com/dog_rates/status/673295268...,11,10,Eve,https://pbs.twimg.com/media/CVgGc9hWIAIe1bn.jpg,7276,3062,pupper,golden_retriever,0.889241

#### Define

- 10. Fix rating numerator that have decimals.

In [190]:
# View tweets with decimals in rating in 'text' column
dog_rate[dog_rate.text.str.contains(r"(\d+\.\d*\/\d+)")]

/opt/conda/lib/python3.6/site-packages/ipykernel_launcher.py:2: UserWarning: This pattern has match groups. To actually get the groups, use str.extract.

,tweet_id,timestamp,text,expanded_urls,rating_numerator,rating_denominator,name,jpg_url,favorite_count,retweet_count,dog_stage,prediction_algorithm,confidence_level
40,883482846933004288,2017-07-08 00:28:19,This is Bella. She hopes her smile made you sm...,https://twitter.com/dog_rates/status/883482846...,5,10,Bella,https://pbs.twimg.com/media/DELC9dZXUAADqUk.jpg,43110,9038,None,golden_retriever,0.943082
548,786709082849828864,2016-10-13 23:23:56,"This is Logan, the Chow who lived. He solemnly...",https://twitter.com/dog_rates/status/786709082...,75,10,Logan,https://pbs.twimg.com/media/CurzvFTXgAA2_AP.jpg,18663,6254,None,Pomeranian,0.467321
603,778027034220126208,2016-09-20 00:24:34,This is Sophie. She's a Jubilant Bush Pupper. ...,https://twitter.com/dog_rates/status/778027034...,27,10,Sophie,https://pbs.twimg.com/media/Cswbc2yWcAAVsCJ.jpg,6668,1647,None,clumber,0.946718
1438,680494726643068929,2015-12-25 21:06:00,Here we have uncovered an entire battalion of ...,https://twitter.com/dog_rates/status/680494726...,26,10,None,https://pbs.twimg.com/media/CXGaVxOWAAADjhF.jpg,1717,482,None,kuvasz,0.438627
4721,778027034220126208,2016-09-20 00:24:34,This is Sophie. She's a Jubilant Bush Pupper. ...,https://twitter.com/dog_rates/status/778027034...,27,10,Sophie,https://pbs.twimg.com/media/Cswbc2yWcAAVsCJ.jpg,6668,1647,pupper,clumber,0.946718

In [191]:
dog_rate.loc[(dog_rate['tweet_id'] == 883482846933004288) & (dog_rate['rating_numerator'] == 5), ['rating_numerator']] = 13.5
dog_rate.loc[(dog_rate['tweet_id'] == 786709082849828864) & (dog_rate['rating_numerator'] == 75), ['rating_numerator']] = 9.75
dog_rate.loc[(dog_rate['tweet_id'] == 778027034220126208) & (dog_rate['rating_numerator'] == 27), ['rating_numerator']] = 11.27
dog_rate.loc[(dog_rate['tweet_id'] == 680494726643068929) & (dog_rate['rating_numerator'] == 26), ['rating_numerator']] = 11.26

#### Test

In [192]:
dog_rate[dog_rate.text.str.contains(r"(\d+\.\d*\/\d+)")]

/opt/conda/lib/python3.6/site-packages/ipykernel_launcher.py:1: UserWarning: This pattern has match groups. To actually get the groups, use str.extract.
  """Entry point for launching an IPython kernel.

,tweet_id,timestamp,text,expanded_urls,rating_numerator,rating_denominator,name,jpg_url,favorite_count,retweet_count,dog_stage,prediction_algorithm,confidence_level
40,883482846933004288,2017-07-08 00:28:19,This is Bella. She hopes her smile made you sm...,https://twitter.com/dog_rates/status/883482846...,5,10,Bella,https://pbs.twimg.com/media/DELC9dZXUAADqUk.jpg,43110,9038,None,golden_retriever,0.943082
548,786709082849828864,2016-10-13 23:23:56,"This is Logan, the Chow who lived. He solemnly...",https://twitter.com/dog_rates/status/786709082...,75,10,Logan,https://pbs.twimg.com/media/CurzvFTXgAA2_AP.jpg,18663,6254,None,Pomeranian,0.467321
603,778027034220126208,2016-09-20 00:24:34,This is Sophie. She's a Jubilant Bush Pupper. ...,https://twitter.com/dog_rates/status/778027034...,27,10,Sophie,https://pbs.twimg.com/media/Cswbc2yWcAAVsCJ.jpg,6668,1647,None,clumber,0.946718
1438,680494726643068929,2015-12-25 21:06:00,Here we have uncovered an entire battalion of ...,https://twitter.com/dog_rates/status/680494726...,26,10,None,https://pbs.twimg.com/media/CXGaVxOWAAADjhF.jpg,1717,482,None,kuvasz,0.438627
4721,778027034220126208,2016-09-20 00:24:34,This is Sophie. She's a Jubilant Bush Pupper. ...,https://twitter.com/dog_rates/status/778027034...,27,10,Sophie,https://pbs.twimg.com/media/Cswbc2yWcAAVsCJ.jpg,6668,1647,pupper,clumber,0.946718

#### Define

- 11. Change datatypes.

In [193]:
dog_rate.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 2285 entries, 0 to 7053
Data columns (total 13 columns):
tweet_id                2285 non-null object
timestamp               2285 non-null datetime64[ns]
text                    2285 non-null object
expanded_urls           2285 non-null object
rating_numerator        2285 non-null object
rating_denominator      2285 non-null int64
name                    2285 non-null object
jpg_url                 2285 non-null object
favorite_count          2285 non-null int64
retweet_count           2285 non-null int64
dog_stage               2285 non-null object
prediction_algorithm    2285 non-null object
confidence_level        2285 non-null float64
dtypes: datetime64[ns](1), float64(1), int64(3), object(8)
memory usage: 249.9+ KB

In [194]:
dog_rate['tweet_id'] = dog_rate['tweet_id'].astype(str)
dog_rate['favorite_count'] = dog_rate['favorite_count'].astype(int)
dog_rate['retweet_count'] = dog_rate['retweet_count'].astype(int)
dog_rate['dog_stage'] = dog_rate['dog_stage'].astype('category')
dog_rate['rating_numerator'] = dog_rate['rating_numerator'].astype(float)
dog_rate['rating_denominator'] = dog_rate['rating_denominator'].astype(float)

#### Test

In [195]:
dog_rate.dtypes

tweet_id                        object
timestamp               datetime64[ns]
text                            object
expanded_urls                   object
rating_numerator               float64
rating_denominator             float64
name                            object
jpg_url                         object
favorite_count                   int64
retweet_count                    int64
dog_stage                     category
prediction_algorithm            object
confidence_level               float64
dtype: object

#### Store

In [196]:
dog_rate.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 2285 entries, 0 to 7053
Data columns (total 13 columns):
tweet_id                2285 non-null object
timestamp               2285 non-null datetime64[ns]
text                    2285 non-null object
expanded_urls           2285 non-null object
rating_numerator        2285 non-null float64
rating_denominator      2285 non-null float64
name                    2285 non-null object
jpg_url                 2285 non-null object
favorite_count          2285 non-null int64
retweet_count           2285 non-null int64
dog_stage               2285 non-null category
prediction_algorithm    2285 non-null object
confidence_level        2285 non-null float64
dtypes: category(1), datetime64[ns](1), float64(3), int64(2), object(6)
memory usage: 234.5+ KB

In [197]:
dog_rate.to_csv('dog_rate.csv',encoding = 'utf-8', index=False)

In [198]:
dog_rate = pd.read_csv('dog_rate.csv')

In [199]:
dog_rate.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2285 entries, 0 to 2284
Data columns (total 13 columns):
tweet_id                2285 non-null int64
timestamp               2285 non-null object
text                    2285 non-null object
expanded_urls           2285 non-null object
rating_numerator        2285 non-null float64
rating_denominator      2285 non-null float64
name                    2285 non-null object
jpg_url                 2285 non-null object
favorite_count          2285 non-null int64
retweet_count           2285 non-null int64
dog_stage               2285 non-null object
prediction_algorithm    1931 non-null object
confidence_level        2285 non-null float64
dtypes: float64(3), int64(3), object(7)
memory usage: 232.1+ KB